// Sorted list of common exercises
export const EXERCISES = [
  "Arnold Press",
  "Back Extension",
  "Barbell Row",
  "Bench Press",
  "Bent Over Row",
  "Bicep Curl",
  "Box Jump",
  "Bulgarian Split Squat",
  "Cable Crossover",
  "Cable Fly",
  "Cable Row",
  "Calf Raise",
  "Chest Fly",
  "Chest Press",
  "Chin Up",
  "Clean",
  "Close Grip Bench Press",
  "Concentration Curl",
  "Deadlift",
  "Decline Bench Press",
  "Dip",
  "Dumbbell Curl",
  "Dumbbell Fly",
  "Dumbbell Press",
  "Dumbbell Row",
  "Face Pull",
  "Farmer's Walk",
  "Front Raise",
  "Front Squat",
  "Goblet Squat",
  "Good Morning",
  "Hack Squat",
  "Hammer Curl",
  "Hanging Leg Raise",
  "Hip Thrust",
  "Incline Bench Press",
  "Incline Dumbbell Press",
  "Kettlebell Swing",
  "Lat Pulldown",
  "Lateral Raise",
  "Leg Curl",
  "Leg Extension",
  "Leg Press",
  "Lunge",
  "Military Press",
  "Overhead Press",
  "Pec Deck",
  "Pendlay Row",
  "Plank",
  "Preacher Curl",
  "Pull Up",
  "Push Up",
  "Reverse Fly",
  "Romanian Deadlift",
  "Rope Tricep Extension",
  "Russian Twist",
  "Seated Cable Row",
  "Seated Calf Raise",
  "Seated Row",
  "Shoulder Press",
  "Shrug",
  "Side Lateral Raise",
  "Sit Up",
  "Skull Crusher",
  "Snatch",
  "Squat",
  "Standing Calf Raise",
  "Sumo Deadlift",
  "T-Bar Row",
  "Thruster",
  "Tricep Dip",
  "Tricep Extension",
  "Tricep Pushdown",
  "Upright Row",
  "Wall Ball",
  "Wide Grip Pull Up",
  "Wrist Curl",
  "Zottman Curl"
].sort();
