// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbsqoqixzrpvgseisgak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpic3FvcWl4enJwdmdzZWlzZ2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTU2NjAsImV4cCI6MjA3NDY3MTY2MH0.10qSePozCKH4ro8zEt3vpMlu4ld0FjtWrwX-vyk7ERU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});